# Laboratory Task 3: Forward and Backward Propagation (NumPy)

<div class="alert alert-block alert-success" style="font-family: Times New Roman">
    <h4><strong>Laboratory Task 3</strong></h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
    <b>Instruction:</b> Perform a forward and backward propagation in python using the inputs from <b>Laboratory Task 2</b>
</p>

```python
x = np.array()
y = np.array()

# use relu as the activation function.

# learning rate
lr = 0.001

```
</div>

### Code Implementation

In [1]:
import numpy as np

# 1. Define Input and Target from Laboratory Task 2
x = np.array([[1.0, 0.0, 1.0]])  # Shape: (1, 3)
y = np.array([[1.0]])             # Shape: (1, 1)

# 2. Initialize Weights and Biases from Laboratory Task 2
W_h = np.array([
    [ 0.2, -0.3],
    [ 0.4,  0.1],
    [-0.5,  0.2]
])                                # Shape: (3, 2)
b_h = np.array([[-0.4, 0.2]])     # Biases theta1, theta2 (1, 2)

W_o = np.array([
    [-0.3],
    [-0.2]
])                                # Shape: (2, 1)
b_o = np.array([[0.1]])           # Bias theta3 (1, 1)

lr = 0.001                        # Learning rate alpha

# 3. Activation Functions
def relu(z):
    return np.maximum(0, z)

def relu_derivative(z):
    return (z > 0).astype(float)

# ----------------- FORWARD PROPAGATION -----------------
Z_h = np.dot(x, W_h) + b_h
H = relu(Z_h)

Z_o = np.dot(H, W_o) + b_o
y_hat = relu(Z_o)

loss = 0.5 * np.sum((y_hat - y) ** 2)

print("=== FORWARD PROPAGATION RESULTS ===")
print(f"Z_h (Hidden Pre-activation): {Z_h}")
print(f"H   (Hidden Activation):     {H}")
print(f"Z_o (Output Pre-activation): {Z_o}")
print(f"y_hat (Model Prediction):    {y_hat}")
print(f"Initial Loss:                {loss:.6f}\n")

# ----------------- BACKWARD PROPAGATION -----------------
delta_o = (y_hat - y) * relu_derivative(Z_o)
delta_h = np.dot(delta_o, W_o.T) * relu_derivative(Z_h)

dW_o = np.dot(H.T, delta_o)
db_o = delta_o

dW_h = np.dot(x.T, delta_h)
db_h = delta_h

# Gradient Descent Updates
W_o_updated = W_o - lr * dW_o
b_o_updated = b_o - lr * db_o
W_h_updated = W_h - lr * dW_h
b_h_updated = b_h - lr * db_h

print("=== BACKWARD PROPAGATION GRADIENTS ===")
print("dW_o:\n", dW_o)
print("db_o:\n", db_o)
print("dW_h:\n", dW_h)
print("db_h:\n", db_h)

print("\n=== UPDATED PARAMETERS (lr = 0.001) ===")
print("Updated W_o:\n", W_o_updated)
print("Updated b_o:\n", b_o_updated)
print("Updated W_h:\n", W_h_updated)
print("Updated b_h:\n", b_h_updated)

=== FORWARD PROPAGATION RESULTS ===
Z_h (Hidden Pre-activation): [[-0.7  0.1]]
H   (Hidden Activation):     [[0.  0.1]]
Z_o (Output Pre-activation): [[0.08]]
y_hat (Model Prediction):    [[0.08]]
Initial Loss:                0.423200

=== BACKWARD PROPAGATION GRADIENTS ===
dW_o:
 [[ 0.   ]
 [-0.092]]
db_o:
 [[-0.92]]
dW_h:
 [[0.    0.184]
 [0.    0.   ]
 [0.    0.184]]
db_h:
 [[0.    0.184]]

=== UPDATED PARAMETERS (lr = 0.001) ===
Updated W_o:
 [[-0.3     ]
 [-0.199908]]
Updated b_o:
 [[0.10092]]
Updated W_h:
 [[ 0.2      -0.300184]
 [ 0.4       0.1     ]
 [-0.5       0.199816]]
Updated b_h:
 [[-0.4       0.199816]]
