# Laboratory Task 5: PyTorch Tensor Operations and Manipulation

<div class="alert alert-block alert-success" style="font-family: Times New Roman">
    <h4><strong>Laboratory Task 5</strong></h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
    <b>Instructions & Prompts:</b>
</p>

<ol>
    <li>Perform Standard Imports</li>
    <li>Create a function called <code>set_seed()</code> that accepts <code>seed: int</code> as a parameter, this function must return nothing but just set the seed to a certain value.</li>
    <li>Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the <code>set_seed()</code> function and use <code>42</code> as the seed parameter.</li>
    <li>Create a tensor "x" from the array above</li>
    <li>Change the dtype of x from <code>int32</code> to <code>int64</code></li>
    <li>Reshape <code>x</code> into a 3x2 tensor</li>
    <li>Return the right-hand column of tensor <code>x</code></li>
    <li>Without changing x, return a tensor of square values of <code>x</code></li>
    <li>Create a tensor <code>y</code> with the same number of elements as <code>x</code>, that can be matrix-multiplied with <code>x</code> (seed 42)</li>
    <li>Find the matrix product of <code>x</code> and <code>y</code>.</li>
</ol>
</div>

### Code Implementation

In [1]:
# 1. Perform Standard Imports
import torch
import numpy as np

# 2. Create set_seed() function
def set_seed(seed: int):
    np.random.seed(seed)
    torch.manual_seed(seed)

# 3. Create a NumPy array 'arr' of 6 random integers between 0 and 5
set_seed(42)
arr = np.random.randint(0, 5, 6)
print("3. NumPy array 'arr':", arr)

# 4. Create tensor x from array
x = torch.from_numpy(arr)
print("4. Tensor x:", x)

# 5. Change dtype of x from int32 to int64
print("5. Old Type:", x.type())
x = x.type(torch.int64)
print("   New Type:", x.type())

# 6. Reshape x into a 3x2 tensor
x = x.reshape(3, 2)
print("6. Reshaped x (3x2):\n", x)

# 7. Return the right-hand column of tensor x
print("7. Right-hand column:\n", x[:, 1:])

# 8. Without changing x, return a tensor of square values of x
x_squared = x.pow(2)
print("8. Squared values:\n", x_squared)
print("   Original x unchanged:\n", x)

# 9. Create tensor y with shape (2, 3) to permit matrix multiplication with x (3, 2)
set_seed(42)
y = torch.randint(0, 5, (2, 3))
print("9. Tensor y (2x3):\n", y)

# 10. Find the matrix product of x and y.
prod = torch.mm(x, y)
print("10. Matrix product prod (3x3):\n", prod)

3. NumPy array 'arr': [3 4 2 4 4 1]
4. Tensor x: tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)
5. Old Type: torch.IntTensor
   New Type: torch.LongTensor
6. Reshaped x (3x2):
 tensor([[3, 4],
        [2, 4],
        [4, 1]])
7. Right-hand column:
 tensor([[4],
        [4],
        [1]])
8. Squared values:
 tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])
   Original x unchanged:
 tensor([[3, 4],
        [2, 4],
        [4, 1]])
9. Tensor y (2x3):
 tensor([[2, 2, 1],
        [4, 1, 0]])
10. Matrix product prod (3x3):
 tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])
